---
title: "Code Book"
output: html_document
---

This is an exercise in data cleaning as part of the Coursera course in Getting and Cleaning Data. The original data from which the code is designed to extract data are part of the Human Activity Recognition Using Smartphones Dataset Version 1.0 (Reyes-Ortiz, Anguita, Ghio & Oneto, 2012)

The data were downloaded from the following repository:

https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip

The following descriptions of variables were taken from the README documentation the original data set. All descriptions, as well as the data processing here shown, should only be taken as the result of a course assignment. If you happen to be interested in the data, please consult the original data directly.

There were 30 participants in the original data set. From each participant, a number of different values were recorded from the accelerometer and gyroscope of their Samsung S2 mobile phones as they performed 1 of 6 different activities (Standing, Sitting, Walking, Walking Upstairs, Walking downstairs, laying)

As explained by (Reyes-Ortiz, Anguita, Ghio & Oneto, 2012) the data here provided come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ. 

I hereby quote the authors when they explain how they registered and processed the main variables:
"The body linear acceleration and angular velocity were derived in time to obtain Jerk signals (tBodyAccJerk-XYZ and tBodyGyroJerk-XYZ). Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, tBodyGyroJerkMag). 
Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag, fBodyGyroMag, fBodyGyroJerkMag. (Note the 'f' to indicate frequency domain signals). 
These signals were used to estimate variables of the feature vector for each pattern:  
'-XYZ' is used to denote 3-axial signals in the X, Y and Z directions".

UNITS= Values of the different measures were normalized and bounded within [-1,1]. Only averages of different mean values and standard deviations are here reported, as requested in the course project assignment.

For further information as well as the original data, please refer to:

[1] Davide Anguita, Alessandro Ghio, Luca Oneto, Xavier Parra and Jorge L. Reyes-Ortiz. Human Activity Recognition on Smartphones using a Multiclass Hardware-Friendly Support Vector Machine. International Workshop of Ambient Assisted Living (IWAAL 2012). Vitoria-Gasteiz, Spain. Dec 2012
